
all:
	mkdir -p replays/PvP
	mkdir -p replays/PvT
	mkdir -p replays/PvZ
	mkdir -p replays/TvT
	mkdir -p replays/TvZ
	mkdir -p replays/ZvZ
	mkdir -p replays/trash
	python unifier.py

clean:
	rm -rf replays/
